SONG = [
    ("A2", "half"), (None, "triplet_eighth"), (None, "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"),
    ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("G1", "triplet_eighth"), ("A2", "quarter"), (None, "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"),
    ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("G1", "triplet_eighth"), ("A2", "quarter"), (None, "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"), ("A2", "triplet_eighth"),
    ("A2", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "eighth"),
    ("A2", "quarter"), ("E1", "dotted_quarter"), ("A2", "eighth"), ("A2", "sixteenth"), ("B2", "sixteenth"), ("C#2", "sixteenth"), ("D2", "sixteenth"),
    ("E2", "half"), (None, "eighth"), ("E2", "eighth"), ("E2", "triplet_eighth"), ("F2", "triplet_eighth"), ("G2", "triplet_eighth"),
    ("A3", "half"), (None, "eighth"), ("A3", "eighth"), ("A3", "triplet_eighth"), ("G2", "triplet_eighth"), ("F2", "triplet_eighth"),
    ("G2", "dotted_eighth"), ("F2", "sixteenth"), ("E2", "half"), ("E2", "quarter"),
    ("D2", "eighth"), ("D2", "sixteenth"), ("E2", "sixteenth"), ("F2", "half"), ("E2", "eighth"), ("D2", "eighth"),
    ("C2", "eighth"), ("C2", "sixteenth"), ("D2", "sixteenth"), ("E2", "half"), ("D2", "eighth"), ("C2", "eighth"),
    ("B2", "eighth"), ("B2", "sixteenth"), ("C#2", "sixteenth"), ("Eb2", "half"), ("F#2", "quarter"),
    ("E2", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "eighth"),
    ("A2", "quarter"), ("E1", "dotted_quarter"), ("A2", "eighth"), ("A2", "sixteenth"), ("B2", "sixteenth"), ("C#2", "sixteenth"), ("D2", "sixteenth"),
    ("E2", "half"), (None, "eighth"), ("E2", "eighth"), ("E2", "triplet_eighth"), ("F2", "triplet_eighth"), ("G2", "triplet_eighth"),
    ("A3", "half"), (None, "quarter"), ("C3", "quarter"),
    ("B3", "quarter"), ("G#2", "half"), ("E2", "quarter"),
    ("F2", "dotted_half"), ("A3", "quarter"),
    ("G#2", "quarter"), ("E2", "half"), ("E2", "quarter"),
    ("F2", "dotted_half"), ("A3", "quarter"),
    ("G#2", "quarter"), ("E2", "half"), ("Eb2", "quarter"),
    ("D2", "dotted_half"), ("F2", "quarter"),
    ("E2", "quarter"), ("C2", "half"), ("A2", "quarter"),
    ("B2", "eighth"), ("B2", "sixteenth"), ("C2", "sixteenth"), ("D2", "half"), ("F2", "quarter"),
    ("E2", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "eighth"),
    ("A2", "quarter"), ("E1", "dotted_quarter"), ("A2", "eighth"), ("A2", "sixteenth"), ("B2", "sixteenth"), ("C#2", "sixteenth"), ("D2", "sixteenth"),
    ("E2", "half"), (None, "eighth"), ("E2", "eighth"), ("E2", "triplet_eighth"), ("F2", "triplet_eighth"), ("G2", "triplet_eighth"),
    ("A3", "half"), (None, "eighth"), ("A3", "eighth"), ("A3", "triplet_eighth"), ("G2", "triplet_eighth"), ("F2", "triplet_eighth"),
    ("G2", "dotted_eighth"), ("F2", "sixteenth"), ("E2", "half"), ("E2", "quarter"),
    ("D2", "eighth"), ("D2", "sixteenth"), ("E2", "sixteenth"), ("F2", "half"), ("E2", "eighth"), ("D2", "eighth"),
    ("C2", "eighth"), ("C2", "sixteenth"), ("D2", "sixteenth"), ("E2", "half"), ("D2", "eighth"), ("C2", "eighth"),
    ("B2", "eighth"), ("B2", "sixteenth"), ("C#2", "sixteenth"), ("Eb2", "half"), ("F#2", "quarter"),
    ("E2", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "eighth"),
    ("A2", "quarter"), ("E1", "dotted_quarter"), ("A2", "eighth"), ("A2", "sixteenth"), ("B2", "sixteenth"), ("C#2", "sixteenth"), ("D2", "sixteenth"),
    ("E2", "half"), (None, "eighth"), ("E2", "eighth"), ("E2", "triplet_eighth"), ("F2", "triplet_eighth"), ("G2", "triplet_eighth"),
    ("A3", "half"), (None, "quarter"), ("C3", "quarter"),
    ("B3", "quarter"), ("G#2", "half"), ("E2", "quarter"),
    ("F2", "dotted_half"), ("A3", "quarter"),
    ("G#2", "quarter"), ("E2", "half"), ("E2", "quarter"),
    ("F2", "dotted_half"), ("A3", "quarter"),
    ("G#2", "quarter"), ("E2", "half"), ("Eb2", "quarter"),
    ("D2", "dotted_half"), ("F2", "quarter"),
    ("E2", "quarter"), ("C2", "half"), ("A2", "quarter"),
    ("B2", "eighth"), ("B2", "sixteenth"), ("C2", "sixteenth"), ("D2", "half"), ("F2", "quarter"),
    ("E2", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "sixteenth"), ("E1", "sixteenth"), ("E1", "eighth"), ("E1", "eighth"),
]
